spring.application.name=account-service
server.port=8081
spring.profiles.active=dev

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

otel.traces.exporter=${OTEL_TRACES_EXPORTER:none}
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
otel.resource.attributes=service.name=account-service